# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    - always_declare_return_types # Declare method return types.
    - always_put_control_body_on_new_line # Separate the control structure expression from its statement.
    - avoid_types_on_closure_parameters # Avoid annotating types for function expression parameters.
    - avoid_unused_constructor_parameters # Avoid defining unused parameters in constructors.
    - cascade_invocations # Cascade consecutive method invocations on the same reference.
    - combinators_ordering # Sort combinator names alphabetically.
    - comment_references # Only reference in scope identifiers in doc comments.
    - directives_ordering # Adhere to Effective Dart Guide directives sorting conventions.
    - discarded_futures # Don’t invoke asynchronous functions in non-async blocks.
    - eol_at_end_of_file # Put a single newline at end of file.
    - matching_super_parameters # Use matching super parameter names.
    - omit_local_variable_types # Omit type annotations for local variables.
    - prefer_const_constructors # Prefer const with constant constructors.
    - prefer_const_constructors_in_immutables # Prefer declaring const constructors on @immutable classes.
    - prefer_const_declarations # Prefer const over final for declarations.
    - prefer_expression_function_bodies # Use => for short members whose body is a single return statement.
    - prefer_final_in_for_each # Prefer final in for-each loop variable if reference is not reassigned.
    - prefer_final_locals # Prefer final for variable declarations if they are not reassigned.
    - prefer_foreach # Use forEach to only apply a function to all the elements.
    - prefer_int_literals # Prefer int literals over double literals.
    - prefer_null_aware_method_calls # Prefer null aware method calls.
    - prefer_relative_imports # Prefer relative imports for files in lib/.
    - prefer_single_quotes # Only use double quotes for strings containing single quotes.
    - require_trailing_commas # Use trailing commas for all function calls and declarations.
    - sort_constructors_first # Sort constructor declarations before other members.
    - test_types_in_equals # Test type arguments in operator ==(Object other).
    - throw_in_finally # Avoid throw in finally block.
    - unawaited_futures # Future results in async function bodies must be awaited or marked unawaited using dart:async.
    - unnecessary_await_in_return # Unnecessary await keyword in return.
    - unnecessary_breaks # Don’t use explicit breaks when a break is implied.
    - unnecessary_lambdas # Don’t create a lambda when a tear-off will do.
    - use_super_parameters # Use super-initializer parameters where possible.

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.inject.dart"

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
